---
baseUrl: "/"
enableRobotsTXT: true
languageCode: en-us
relativeURLs: false
title: MIT OpenCourseWare
theme: ["base-theme", "course"]
ignoreErrors: ["error-remote-getjson"]
security:
  funcs:
    getenv:
    - ^HUGO_
    - GTM_ACCOUNT_ID
    - RESOURCE_BASE_URL
    - STATIC_API_BASE_URL
    - OCW_STUDIO_BASE_URL
    - OCW_IMPORT_STARTER_SLUG
    - COURSE_BASE_URL