---
baseUrl: "/"
enableRobotsTXT: true
languageCode: en-us
relativeURLs: false
title: MIT OpenCourseWare
caches:
  getjson:
    maxAge: 5m
mediaTypes:
  application/json:
    suffixes:
      - json
outputs:
  page:
    - HTML
    - JSON
theme: ["base-theme", "www"]
